# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('postid', models.IntegerField(max_length=16)),
                ('image', models.ImageField(upload_to='image')),
                ('like_num', models.IntegerField(max_length=16)),
            ],
        ),
    ]
