# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180307_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='request_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
