# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movies_request_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
