# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180307_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
